name: chacra-env
channels:
  - conda-forge
  - defaults

dependencies:
  - femto
  - openmm=8.1.2 
  - mpi=1.0=openmpi
  - openmpi>=4.1         
  - mpi4py                
  - cuda-version>=12.0,<12.5
  - cuda-cudart=12.4.*
  - cuda-cudart_linux-64=12.4.*
  - cuda-nvrtc=12.4.*
  - cuda-cupti=12.4.*
  - cuda-libraries=12.4.*
  - cuda-runtime=12.4.*      
  - ucx>=1.15
  - ucx-proc=*=gpu        
  - nccl                  
  - mdanalysis>=2.9.0
  - pdbfixer
  - pandas
  - scipy
  - tqdm
  - matplotlib
  - scikit-learn  
  - networkx
  - nglview
  - pre-commit
  # most likely later versions of vmd-python > 3.1.4 
  # or python>3.11 are causing the memory allocation error with get_dynamic_contacts.py
  # but can't get multi-gpu to run with < Python 3.12
  - vmd-python
  - prolif
  
    
